source 'https://rubygems.org'

gem 'rake'
gem 'erubis', '~> 2.7.0'

# Point padrino to Rubygems once http://git.io/ll8xtA is merged
gem 'padrino', github: 'padrino/padrino-framework' # '~> 0.13.0'

gem 'bh', path: '../../../bh'